### ISSUE TITLE
[Question] Is there any way to build with stack?

### ISSUE THREAD

**Issue by McOmghall** [Euterpea/Euterpea2#3]
I'm new to Haskell and I'm making my projects on stack, so I noticed your package and some dependents aren't in the curated packages. Do you happen to know of a guide to build this package over slack? Thanks in advance.

**Comment by McOmghall** [comment]
Nevermind, just noticed euterpea 2 is not in hackage so I imported it from git directly.
packages:
```
- '.'
- location:
    git: https://github.com/Euterpea/Euterpea2.git
    commit: 7a5e865406dc8dc8d2bd730b7625656fc4c80036
extra-deps: 
  - containers-0.5.6.2
  - heap-0.6.0
  - PortMidi-0.1.5.2
  - arrows-0.4.4.1
  - midi-0.2.2
  - Stream-0.4.7.2
  - event-list-0.1.1.3
  - monoid-transformer-0.0.3
  - non-negative-0.1.1
  - lazysmallcheck-0.6
```
